// import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/Header";
import "./globals.css";
// import LoadingProvider from "@/components/LoadingProvider";

import localFont from "next/font/local";

const degular = localFont({
  src: [
    {
      path: "../public/fonts/DegularDemo-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/DegularDemo-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-degular",
});
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${degular.className} antialiased overflow-x-hidden`}>
        <Header />

        {/* <LoadingProvider> */}
          {children}
        {/* </LoadingProvider> */}
      </body>
    </html>
  );
}
